function fft_biplex_init_xblock(FFTSize, input_bit_width, coeff_bit_width, add_latency, mult_latency, bram_latency, conv_latency, quantization, overflow, arch, opt_target, coeffs_bit_limit, delays_bit_limit, specify_mult, mult_spec, hardcode_shifts, shift_schedule, dsp48_adders)



%% inports
xlsub2_sync = xInport('sync');
xlsub2_shift = xInport('shift');
xlsub2_pol1 = xInport('pol1');
xlsub2_pol2 = xInport('pol2');

%% outports
xlsub2_sync_out = xOutport('sync_out');
xlsub2_pol1_out = xOutport('pol1_out');
xlsub2_pol2_out = xOutport('pol2_out');
xlsub2_of = xOutport('of');

%% diagram

% block: temp_fft_biplex/fft_biplex1/biplex_core
xlsub2_biplex_core_out1 = xSignal;
xlsub2_biplex_core_out2 = xSignal;
xlsub2_biplex_core_out3 = xSignal;
xlsub2_biplex_core_sub = xBlock(struct('source', str2func('fft_biplex_core_init_xblock'), 'name', 'biplex_core'), ...
                                 struct( 'FFTSize', FFTSize,...
                                        'input_bit_width', input_bit_width,...
                                        'coeff_bit_width', coeff_bit_width,...
                                        'quantization', quantization,...
                                        'overflow', overflow,...
                                        'add_latency', add_latency,...
                                        'mult_latency', mult_latency,...
                                        'bram_latency', bram_latency,...
                                        'conv_latency', conv_latency, ...
                                        'arch', arch, ...
                                        'opt_target', opt_target, ...
                                        'coeffs_bit_limit', coeffs_bit_limit, ...
                                        'delays_bit_limit', delays_bit_limit, ...
                                        'hardcore_shifts',hardcode_shifts,...
                                        'shift_schedule', shift_schedule, ...
                                        'specify_mult', specify_mult, ...
                                        'mult_spec', mult_spec, ...
                                        'dsp48_adders', dsp48_adders), ... % {3, 18, 18, 1, 2, 2, 1, 'Round  (unbiased: +/- Inf)', 'Saturate', 'Virtex5', 'logic', 8, 8, 'off', getfield( getfield( get_param( gcb,'UserData' ), 'parameters'),'mult_spec'), 'off', getfield( getfield( get_param( gcb,'UserData' ), 'parameters'),'shift_schedule'), 'off'}, ...
                            {xlsub2_sync, xlsub2_shift, xlsub2_pol1, xlsub2_pol2}, ...
                            {xlsub2_biplex_core_out1, xlsub2_biplex_core_out2, xlsub2_biplex_core_out3, xlsub2_of});

% block: temp_fft_biplex/fft_biplex1/biplex_cplx_unscrambler
xlsub2_biplex_cplx_unscrambler_sub = xBlock(struct('source',str2func('biplex_cplx_unscrambler_init_xblock'), 'name', 'biplex_cplx_unscrambler'), ...
                                        {FFTSize,bram_latency},...
                                        {xlsub2_biplex_core_out2, xlsub2_biplex_core_out3, xlsub2_biplex_core_out1}, ...
                                        {xlsub2_pol1_out, xlsub2_pol2_out, xlsub2_sync_out});



end

