function xlsub5_butterfly_direct(biplex, FFTSize, Coeffs, StepPeriod, coeff_bit_width, input_bit_width, downshift, add_latency, mult_latency, bram_latency, conv_latency, quantization, overflow, arch, opt_target, coeffs_bram, use_hdl, use_embedded, hardcode_shifts, dsp48_adders)



%% inports
xlsub6_a = xInport('a');
xlsub6_b = xInport('b');
xlsub6_sync = xInport('sync');
xlsub6_shift = xInport('shift');

%% outports
xlsub6_outport1 = xOutport('a+bw');
xlsub6_a_bw = xOutport('a-bw');
xlsub6_of = xOutport('of');
xlsub6_sync_out = xOutport('sync_out');

%% diagram

% block: single_pol_xblock_tb/fft_wideband_real1/fft_biplex_real_4x0/biplex_core/fft_stage_1/butterfly_direct/Logical
xlsub6_convert_of0_out2 = xSignal;
xlsub6_convert_of1_out2 = xSignal;
xlsub6_convert_of2_out2 = xSignal;
xlsub6_convert_of3_out2 = xSignal;
xlsub6_Logical = xBlock(struct('source', 'Logical', 'name', 'Logical'), ...
                        struct('logical_function', 'OR', ...
                               'inputs', 4), ...
                        {xlsub6_convert_of0_out2, xlsub6_convert_of1_out2, xlsub6_convert_of2_out2, xlsub6_convert_of3_out2}, ...
                        {xlsub6_of});

% block: single_pol_xblock_tb/fft_wideband_real1/fft_biplex_real_4x0/biplex_core/fft_stage_1/butterfly_direct/Scale0
xlsub6_cadd_out1 = xSignal;
xlsub6_Scale0_out1 = xSignal;
xlsub6_Scale0 = xBlock(struct('source', 'Scale', 'name', 'Scale0'), ...
                       struct('scale_factor', -1), ...
                       {xlsub6_cadd_out1}, ...
                       {xlsub6_Scale0_out1});

% block: single_pol_xblock_tb/fft_wideband_real1/fft_biplex_real_4x0/biplex_core/fft_stage_1/butterfly_direct/Scale1
xlsub6_cadd_out2 = xSignal;
xlsub6_Scale1_out1 = xSignal;
xlsub6_Scale1 = xBlock(struct('source', 'Scale', 'name', 'Scale1'), ...
                       struct('scale_factor', -1), ...
                       {xlsub6_cadd_out2}, ...
                       {xlsub6_Scale1_out1});

% block: single_pol_xblock_tb/fft_wideband_real1/fft_biplex_real_4x0/biplex_core/fft_stage_1/butterfly_direct/Scale2
xlsub6_csub_out1 = xSignal;
xlsub6_Scale2_out1 = xSignal;
xlsub6_Scale2 = xBlock(struct('source', 'Scale', 'name', 'Scale2'), ...
                       struct('scale_factor', -1), ...
                       {xlsub6_csub_out1}, ...
                       {xlsub6_Scale2_out1});

% block: single_pol_xblock_tb/fft_wideband_real1/fft_biplex_real_4x0/biplex_core/fft_stage_1/butterfly_direct/Scale3
xlsub6_csub_out2 = xSignal;
xlsub6_Scale3_out1 = xSignal;
xlsub6_Scale3 = xBlock(struct('source', 'Scale', 'name', 'Scale3'), ...
                       struct('scale_factor', -1), ...
                       {xlsub6_csub_out2}, ...
                       {xlsub6_Scale3_out1});


% block: single_pol_xblock_tb/fft_wideband_real1/fft_biplex_real_4x0/biplex_core/fft_stage_1/butterfly_direct/ri_to_c01
xlsub6_convert_of0_out1 = xSignal;
xlsub6_convert_of1_out1 = xSignal;
xlsub6_ri_to_c01 = xBlock(struct('source', 'casper_library_misc/ri_to_c', 'name', 'ri_to_c01'), ...
                          [], ...
                          {xlsub6_convert_of0_out1, xlsub6_convert_of1_out1}, ...
                          {xlsub6_outport1});

% block: single_pol_xblock_tb/fft_wideband_real1/fft_biplex_real_4x0/biplex_core/fft_stage_1/butterfly_direct/ri_to_c23
xlsub6_convert_of2_out1 = xSignal;
xlsub6_convert_of3_out1 = xSignal;
xlsub6_ri_to_c23 = xBlock(struct('source', 'casper_library_misc/ri_to_c', 'name', 'ri_to_c23'), ...
                          [], ...
                          {xlsub6_convert_of2_out1, xlsub6_convert_of3_out1}, ...
                          {xlsub6_a_bw});

% block: single_pol_xblock_tb/fft_wideband_real1/fft_biplex_real_4x0/biplex_core/fft_stage_1/butterfly_direct/sync_delay
xlsub6_twiddle_pass_through_out5 = xSignal;
xlsub6_sync_delay = xBlock(struct('source', 'Delay', 'name', 'sync_delay'), ...
                           struct('latency', 3, ...
                                  'reg_retiming', 'on'), ...
                           {xlsub6_twiddle_pass_through_out5}, ...
                           {xlsub6_sync_out});

% block: single_pol_xblock_tb/fft_wideband_real1/fft_biplex_real_4x0/biplex_core/fft_stage_1/butterfly_direct/twiddle_pass_through
xlsub6_twiddle_pass_through_out1 = xSignal;
xlsub6_twiddle_pass_through_out2 = xSignal;
xlsub6_twiddle_pass_through_out3 = xSignal;
xlsub6_twiddle_pass_through_out4 = xSignal;
xlsub6_twiddle_pass_through = xBlock(struct('source', 'casper_library_ffts_twiddle/twiddle_pass_through', 'name', 'twiddle_pass_through'), ...
                                     struct('FFTSize', 8, ...
                                            'add_latency', 2, ...
                                            'mult_latency', 3, ...
                                            'bram_latency', 2, ...
                                            'conv_latency', 1), ...
                                     {xlsub6_a, xlsub6_b, xlsub6_sync}, ...
                                     {xlsub6_twiddle_pass_through_out1, xlsub6_twiddle_pass_through_out2, xlsub6_twiddle_pass_through_out3, xlsub6_twiddle_pass_through_out4, xlsub6_twiddle_pass_through_out5});

% block: single_pol_xblock_tb/fft_wideband_real1/fft_biplex_real_4x0/biplex_core/fft_stage_1/butterfly_direct/cadd
xlsub6_cadd_sub = xBlock(struct('source', str2func('cadd'), 'name', 'cadd'), ...
                     {'Addition', 18, 17, 18, 17, 'on', 19, 17, 'Truncate', 'Wrap', 0}, ...
                     {xlsub6_twiddle_pass_through_out1, xlsub6_twiddle_pass_through_out2, xlsub6_twiddle_pass_through_out3, xlsub6_twiddle_pass_through_out4}, ...
                     {xlsub6_cadd_out1, xlsub6_cadd_out2});

% block: single_pol_xblock_tb/fft_wideband_real1/fft_biplex_real_4x0/biplex_core/fft_stage_1/butterfly_direct/convert_of0
xlsub6_convert_of0_sub = xBlock(struct('source', str2func('convert_of'), 'name', 'convert_of0'), ...
                            {19, 18, 18, 17, 1, 'Wrap', 'Truncate'}, ...
                            {xlsub6_Scale0_out1}, ...
                            {xlsub6_convert_of0_out1, xlsub6_convert_of0_out2});

% block: single_pol_xblock_tb/fft_wideband_real1/fft_biplex_real_4x0/biplex_core/fft_stage_1/butterfly_direct/convert_of1
xlsub6_convert_of1_sub = xBlock(struct('source', str2func('convert_of'), 'name', 'convert_of1'), ...
                            {19, 18, 18, 17, 1, 'Wrap', 'Truncate'}, ...
                            {xlsub6_Scale1_out1}, ...
                            {xlsub6_convert_of1_out1, xlsub6_convert_of1_out2});

% block: single_pol_xblock_tb/fft_wideband_real1/fft_biplex_real_4x0/biplex_core/fft_stage_1/butterfly_direct/convert_of2
xlsub6_convert_of2_sub = xBlock(struct('source', str2func('convert_of'), 'name', 'convert_of2'), ...
                            {19, 18, 18, 17, 1, 'Wrap', 'Truncate'}, ...
                            {xlsub6_Scale2_out1}, ...
                            {xlsub6_convert_of2_out1, xlsub6_convert_of2_out2});

% block: single_pol_xblock_tb/fft_wideband_real1/fft_biplex_real_4x0/biplex_core/fft_stage_1/butterfly_direct/convert_of3
xlsub6_convert_of3_sub = xBlock(struct('source',str2func('convert_of'), 'name', 'convert_of3'), ...
                            {19, 18, 18, 17, 1, 'Wrap', 'Truncate'}, ...
                            {xlsub6_Scale3_out1}, ...
                            {xlsub6_convert_of3_out1, xlsub6_convert_of3_out2});

% block: single_pol_xblock_tb/fft_wideband_real1/fft_biplex_real_4x0/biplex_core/fft_stage_1/butterfly_direct/csub
xlsub6_csub_sub = xBlock(struct('source', str2func('csub'), 'name', 'csub'), ...
                     {'Subtraction', 18, 17, 18, 17, 'on', 19, 17, 'Truncate', 'Wrap', 0}, ...
                     {xlsub6_twiddle_pass_through_out1, xlsub6_twiddle_pass_through_out2, xlsub6_twiddle_pass_through_out3, xlsub6_twiddle_pass_through_out4}, ...
                     {xlsub6_csub_out1, xlsub6_csub_out2});
end
					 