cmult_dsp48e_init(gcb, ...
    'n_bits_a', n_bits_a, ...
    'bin_pt_a', bin_pt_a, ...
    'n_bits_b', n_bits_b, ...
    'bin_pt_b', bin_pt_b, ...
    'conjugated', conjugated, ...
    'full_precision', full_precision, ...
    'n_bits_c', n_bits_c, ...
    'bin_pt_c', bin_pt_c, ...
    'quantization', quantization, ...
    'overflow', overflow, ...
    'cast_latency', cast_latency);