cmult_init(gcb, ...
    'n_bits_a',n_bits_a, ...
    'bin_pt_a',bin_pt_a, ...
    'n_bits_b',n_bits_b, ...
    'bin_pt_b',bin_pt_b, ...
    'n_bits_ab',n_bits_ab, ...
    'bin_pt_ab',bin_pt_ab, ...
    'quantization',quantization, ...
    'overflow', overflow, ...
    'mult_latency', mult_latency, ...
    'add_latency', add_latency, ...
    'conjugated', conjugated);