coeff_gen_init( gcb, ...
    'Coeffs', Coeffs, ...
    'coeff_bit_width', coeff_bit_width, ...
    'StepPeriod', StepPeriod, ...
    'bram_latency', bram_latency, ...
    'coeffs_bram', coeffs_bram);
