function xlsub6_convert_of1(bit_width_i, binary_point_i, bit_width_o, binary_point_o, latency, overflow, quantization)



%% inports
xlsub7_din = xInport('din');

%% outports
xlsub7_dout = xOutport('dout');
xlsub7_of = xOutport('of');

%% diagram

% block: single_pol_xblock_tb/fft_wideband_real1/fft_biplex_real_4x0/biplex_core/fft_stage_1/butterfly_direct/convert_of1/convert
xlsub7_convert = xBlock(struct('source', 'Convert', 'name', 'convert'), ...
                        struct('n_bits', bit_width_o, ...
                               'bin_pt', binary_point_o, ...
                               'latency', latency, ...
                               'pipeline', 'on'), ...
                        {xlsub7_din}, ...
                        {xlsub7_dout});

% block: single_pol_xblock_tb/fft_wideband_real1/fft_biplex_real_4x0/biplex_core/fft_stage_1/butterfly_direct/convert_of1/never
xlsub7_never = xBlock(struct('source', 'Constant', 'name', 'never'), ...
                      struct('arith_type', 'Boolean', ...
                             'const', 0, ...
                             'explicit_period', 'on'), ...
                      {}, ...
                      {xlsub7_of});



end