function Datatype_Conv_Cos(theta_binary_bits, fft_bits)
% This is a generated function based on subsystem:
%     more_delays/Datatype_Conv_Cos
% Though there are limitations about the generated script, 
% the main purpose of this utility is to make learning
% Sysgen Script easier.
% 
% To test it, run the following commands from MATLAB console:
% cfg.source = str2func('Datatype_Conv_Cos');
% cfg.toplevel = 'more_delays/Datatype_Conv_Cos';
% args = {my_theta_binary_bits, my_fft_bits};
% xBlock(cfg, args);
% 
% You can edit Datatype_Conv_Cos.m to debug your script.
% 
% You can also replace the MaskInitialization code with the 
% following commands so the subsystem will be generated 
% according to the values of mask parameters.
% cfg.source = str2func('Datatype_Conv_Cos');
% cfg.toplevel = gcb;
% args = {theta_binary_bits, fft_bits};
% xBlock(cfg, args);
% 
% To configure the xBlock call in debug mode, in which mode,
% autolayout will be performed every time a block is added,
% run the following commands:
% cfg.source = str2func('Datatype_Conv_Cos');
% cfg.toplevel = gcb;
% cfg.debug = 1;
% args = {theta_binary_bits, fft_bits};
% xBlock(cfg, args);
% 
% To make the xBlock smart so it won't re-generate the
% subsystem if neither the arguments nor the scripts are
% changes, use as the following:
% cfg.source = str2func('Datatype_Conv_Cos');
% cfg.toplevel = gcb;
% cfg.depend = {'Datatype_Conv_Cos'};
% args = {theta_binary_bits, fft_bits};
% xBlock(cfg, args);
% 
% See also xBlock, xInport, xOutport, xSignal, xlsub2script.


%% inports
xlsub2_In1 = xInport('In1');

%% outports
xlsub2_out0 = xOutport('out0');

%% diagram

% block: more_delays/Datatype_Conv_Cos/Concat10
xlsub2_Slice32_out1 = xSignal;
xlsub2_Mux10_out1 = xSignal;
xlsub2_Concat10_out1 = xSignal;
xlsub2_Concat10 = xBlock(struct('source', 'Concat', 'name', 'Concat10'), ...
                         [], ...
                         {xlsub2_Slice32_out1, xlsub2_Mux10_out1}, ...
                         {xlsub2_Concat10_out1});

% block: more_delays/Datatype_Conv_Cos/Concat11
xlsub2_Relational19_out1 = xSignal;
xlsub2_Relational17_out1 = xSignal;
xlsub2_Concat11_out1 = xSignal;
xlsub2_Concat11 = xBlock(struct('source', 'Concat', 'name', 'Concat11'), ...
                         [], ...
                         {xlsub2_Relational19_out1, xlsub2_Relational17_out1}, ...
                         {xlsub2_Concat11_out1});

% block: more_delays/Datatype_Conv_Cos/Constant26
xlsub2_Constant26_out1 = xSignal;
xlsub2_Constant26 = xBlock(struct('source', 'Constant', 'name', 'Constant26'), ...
                           struct('arith_type', 'Unsigned', ...
                                  'n_bits', 3, ...
                                  'bin_pt', 0), ...
                           {}, ...
                           {xlsub2_Constant26_out1});

% block: more_delays/Datatype_Conv_Cos/Constant27
xlsub2_Constant27_out1 = xSignal;
xlsub2_Constant27 = xBlock(struct('source', 'Constant', 'name', 'Constant27'), ...
                           struct('arith_type', 'Unsigned', ...
                                  'const', 2^(theta_binary_bits)-1, ...
                                  'n_bits', theta_binary_bits, ...
                                  'bin_pt', 0), ...
                           {}, ...
                           {xlsub2_Constant27_out1});

% block: more_delays/Datatype_Conv_Cos/Constant28
xlsub2_Constant28_out1 = xSignal;
xlsub2_Constant28 = xBlock(struct('source', 'Constant', 'name', 'Constant28'), ...
                           struct('n_bits', 20, ...
                                  'bin_pt', 17), ...
                           {}, ...
                           {xlsub2_Constant28_out1});

% block: more_delays/Datatype_Conv_Cos/Constant29
xlsub2_Constant29_out1 = xSignal;
xlsub2_Constant29 = xBlock(struct('source', 'Constant', 'name', 'Constant29'), ...
                           struct('const', -1, ...
                                  'n_bits', 20, ...
                                  'bin_pt', 17), ...
                           {}, ...
                           {xlsub2_Constant29_out1});

% block: more_delays/Datatype_Conv_Cos/Convert6
xlsub2_Convert6_out1 = xSignal;
xlsub2_Convert6 = xBlock(struct('source', 'Convert', 'name', 'Convert6'), ...
                         struct('n_bits', fft_bits, ...
                                'bin_pt', 0), ...
                         {xlsub2_Concat10_out1}, ...
                         {xlsub2_Convert6_out1});

% block: more_delays/Datatype_Conv_Cos/Delay7
xlsub2_Delay7_out1 = xSignal;
xlsub2_Delay7 = xBlock(struct('source', 'Delay', 'name', 'Delay7'), ...
                       [], ...
                       {xlsub2_In1}, ...
                       {xlsub2_Delay7_out1});

% block: more_delays/Datatype_Conv_Cos/Mux10
xlsub2_Relational18_out1 = xSignal;
xlsub2_Slice37_out1 = xSignal;
xlsub2_Mux10 = xBlock(struct('source', 'Mux', 'name', 'Mux10'), ...
                      [], ...
                      {xlsub2_Relational18_out1, xlsub2_Slice37_out1, xlsub2_Constant27_out1}, ...
                      {xlsub2_Mux10_out1});

% block: more_delays/Datatype_Conv_Cos/Mux9
xlsub2_Mux9_out1 = xSignal;
xlsub2_Mux9 = xBlock(struct('source', 'Mux', 'name', 'Mux9'), ...
                     struct('inputs', '3'), ...
                     {xlsub2_Concat11_out1, xlsub2_Delay7_out1, xlsub2_Constant29_out1, xlsub2_Constant28_out1}, ...
                     {xlsub2_Mux9_out1});

% block: more_delays/Datatype_Conv_Cos/Reinterpret10
xlsub2_Reinterpret10_out1 = xSignal;
xlsub2_Reinterpret10 = xBlock(struct('source', 'Reinterpret', 'name', 'Reinterpret10'), ...
                              struct('force_bin_pt', 'on', ...
                                     'bin_pt', fft_bits-1), ...
                              {xlsub2_Convert6_out1}, ...
                              {xlsub2_Reinterpret10_out1});

% block: more_delays/Datatype_Conv_Cos/Relational17
xlsub2_Relational17 = xBlock(struct('source', 'Relational', 'name', 'Relational17'), ...
                             struct('mode', 'a<b'), ...
                             {xlsub2_In1, xlsub2_Constant29_out1}, ...
                             {xlsub2_Relational17_out1});

% block: more_delays/Datatype_Conv_Cos/Relational18
xlsub2_Slice34_out1 = xSignal;
xlsub2_Relational18 = xBlock(struct('source', 'Relational', 'name', 'Relational18'), ...
                             struct('latency', 0), ...
                             {xlsub2_Slice34_out1, xlsub2_Constant26_out1}, ...
                             {xlsub2_Relational18_out1});

% block: more_delays/Datatype_Conv_Cos/Relational19
xlsub2_Relational19 = xBlock(struct('source', 'Relational', 'name', 'Relational19'), ...
                             struct('mode', 'a>b'), ...
                             {xlsub2_In1, xlsub2_Constant28_out1}, ...
                             {xlsub2_Relational19_out1});



% block: more_delays/Datatype_Conv_Cos/Slice32
xlsub2_Slice32 = xBlock(struct('source', 'Slice', 'name', 'Slice32'), ...
                        [], ...
                        {xlsub2_Mux9_out1}, ...
                        {xlsub2_Slice32_out1});

% block: more_delays/Datatype_Conv_Cos/Slice33
xlsub2_Slice33_out1 = xSignal;
xlsub2_Slice33 = xBlock(struct('source', 'Slice', 'name', 'Slice33'), ...
                        struct('nbits', 3), ...
                        {xlsub2_Mux9_out1}, ...
                        {xlsub2_Slice33_out1});

% block: more_delays/Datatype_Conv_Cos/Slice34
xlsub2_Slice34 = xBlock(struct('source', 'Slice', 'name', 'Slice34'), ...
                        struct('nbits', 3), ...
                        {xlsub2_Mux9_out1}, ...
                        {xlsub2_Slice34_out1});

% block: more_delays/Datatype_Conv_Cos/Slice35
xlsub2_Slice35_out1 = xSignal;
xlsub2_Slice35 = xBlock(struct('source', 'Slice', 'name', 'Slice35'), ...
                        [], ...
                        {xlsub2_Mux9_out1}, ...
                        {xlsub2_Slice35_out1});

% block: more_delays/Datatype_Conv_Cos/Slice36
xlsub2_Slice36_out1 = xSignal;
xlsub2_Slice36 = xBlock(struct('source', 'Slice', 'name', 'Slice36'), ...
                        struct('bit1', -1), ...
                        {xlsub2_Mux9_out1}, ...
                        {xlsub2_Slice36_out1});

% block: more_delays/Datatype_Conv_Cos/Slice37
xlsub2_Slice37 = xBlock(struct('source', 'Slice', 'name', 'Slice37'), ...
                        struct('nbits', theta_binary_bits, ...
                               'mode', 'Lower Bit Location + Width'), ...
                        {xlsub2_Mux9_out1}, ...
                        {xlsub2_Slice37_out1});

% block: more_delays/Datatype_Conv_Cos/Slice38
xlsub2_Slice38_out1 = xSignal;
xlsub2_Slice38 = xBlock(struct('source', 'Slice', 'name', 'Slice38'), ...
                        struct('bit1', -2), ...
                        {xlsub2_Mux9_out1}, ...
                        {xlsub2_Slice38_out1});

% extra outport assignment
xlsub2_out0.assign(xlsub2_Reinterpret10_out1);


end

