function delay_bram_prog(MaxDelay, bram_latency)
% This is a generated function based on subsystem:
%     untitled/delay_bram_prog
% Though there are limitations about the generated script, 
% the main purpose of this utility is to make learning
% Sysgen Script easier.
% 
% To test it, run the following commands from MATLAB console:
% cfg.source = str2func('delay_bram_prog');
% cfg.toplevel = 'untitled/delay_bram_prog';
% args = {my_MaxDelay, my_bram_latency};
% xBlock(cfg, args);
% 
% You can edit delay_bram_prog.m to debug your script.
% 
% You can also replace the MaskInitialization code with the 
% following commands so the subsystem will be generated 
% according to the values of mask parameters.
% cfg.source = str2func('delay_bram_prog');
% cfg.toplevel = gcb;
% args = {MaxDelay, bram_latency};
% xBlock(cfg, args);
% 
% To configure the xBlock call in debug mode, in which mode,
% autolayout will be performed every time a block is added,
% run the following commands:
% cfg.source = str2func('delay_bram_prog');
% cfg.toplevel = gcb;
% cfg.debug = 1;
% args = {MaxDelay, bram_latency};
% xBlock(cfg, args);
% 
% To make the xBlock smart so it won't re-generate the
% subsystem if neither the arguments nor the scripts are
% changes, use as the following:
% cfg.source = str2func('delay_bram_prog');
% cfg.toplevel = gcb;
% cfg.depend = {'delay_bram_prog'};
% args = {MaxDelay, bram_latency};
% xBlock(cfg, args);
% 
% See also xBlock, xInport, xOutport, xSignal, xlsub2script.


%% inports
xlsub2_din = xInport('din');
xlsub2_delay = xInport('delay');

%% outports
xlsub2_dout = xOutport('dout');

%% diagram

% block: untitled/delay_bram_prog/AddSub
xlsub2_Constant1_out1 = xSignal;
xlsub2_AddSub_out1 = xSignal;
xlsub2_AddSub = xBlock(struct('source', 'AddSub', 'name', 'AddSub'), ...
                       struct('mode', 'Subtraction', ...
                              'latency', 2, ...
                              'precision', 'User Defined', ...
                              'n_bits', MaxDelay, ...
                              'bin_pt', 0, ...
                              'use_behavioral_HDL', 'on', ...
                              'use_rpm', 'on'), ...
                       {xlsub2_delay, xlsub2_Constant1_out1}, ...
                       {xlsub2_AddSub_out1});

% block: untitled/delay_bram_prog/Constant1
xlsub2_Constant1 = xBlock(struct('source', 'Constant', 'name', 'Constant1'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', bram_latency + 1, ...
                                 'n_bits', MaxDelay, ...
                                 'bin_pt', 0, ...
                                 'explicit_period', 'on'), ...
                          {}, ...
                          {xlsub2_Constant1_out1});

% block: untitled/delay_bram_prog/Constant2
xlsub2_Constant2_out1 = xSignal;
xlsub2_Constant2 = xBlock(struct('source', 'Constant', 'name', 'Constant2'), ...
                          struct('arith_type', 'Boolean', ...
                                 'n_bits', 1, ...
                                 'bin_pt', 0, ...
                                 'explicit_period', 'on'), ...
                          {}, ...
                          {xlsub2_Constant2_out1});

% block: untitled/delay_bram_prog/Counter
xlsub2_Relational_out1 = xSignal;
xlsub2_Counter_out1 = xSignal;
xlsub2_Counter = xBlock(struct('source', 'Counter', 'name', 'Counter'), ...
                        struct('cnt_to', inf, ...
                               'n_bits', MaxDelay, ...
                               'rst', 'on', ...
                               'use_rpm', 'off'), ...
                        {xlsub2_Relational_out1}, ...
                        {xlsub2_Counter_out1});

% block: untitled/delay_bram_prog/Relational
xlsub2_Relational = xBlock(struct('source', 'Relational', 'name', 'Relational'), ...
                           struct('mode', 'a>=b', ...
                                  'latency', 0), ...
                           {xlsub2_Counter_out1, xlsub2_AddSub_out1}, ...
                           {xlsub2_Relational_out1});

% block: untitled/delay_bram_prog/Single Port RAM
xlsub2_Single_Port_RAM = xBlock(struct('source', 'Single Port RAM', 'name', 'Single Port RAM'), ...
                                struct('depth', 2^MaxDelay, ...
                                       'initVector', 0, ...
                                       'write_mode', 'Read Before Write', ...
                                       'latency', bram_latency, ...
                                       'use_rpm', 'off'), ...
                                {xlsub2_Counter_out1, xlsub2_din, xlsub2_Constant2_out1}, ...
                                {xlsub2_dout});



end

