% delay_complex block mask init back up
delay_complex_init(gcb, ...
    'delay', delay, ...
    'n_bits', n_bits, ...
    'bin_pt', bin_pt, ...
    'use_bram', use_bram, ...
    'bram_latency', bram_latency);