twiddle_general_4mult_init(gcb, ...
    'Coeffs', Coeffs, ...
    'StepPeriod', StepPeriod, ...
    'coeffs_bram', coeffs_bram, ...
    'coeff_bit_width', coeff_bit_width, ...
    'input_bit_width', input_bit_width, ...
    'add_latency', add_latency, ...
    'mult_latency', mult_latency, ...
    'bram_latency', bram_latency, ...
    'conv_latency', conv_latency, ...
    'arch', arch, ...
    'use_hdl', use_hdl, ...
    'use_embedded', use_embedded, ...
    'quantization', quantization, ...
    'overflow', overflow)