function twiddle_stage_2(FFTSize, input_bit_width, add_latency, mult_latency, bram_latency, conv_latency, opt_target)
% This is a generated function based on subsystem:
%     twiddles_collections/twiddle_stage_2
% Though there are limitations about the generated script, 
% the main purpose of this utility is to make learning
% Sysgen Script easier.
% 
% To test it, run the following commands from MATLAB console:
% cfg.source = str2func('twiddle_stage_2');
% cfg.toplevel = 'twiddles_collections/twiddle_stage_2';
% args = {my_FFTSize, my_input_bit_width, my_add_latency, my_mult_latency, my_bram_latency, my_conv_latency, my_opt_target};
% xBlock(cfg, args);
% 
% You can edit twiddle_stage_2.m to debug your script.
% 
% You can also replace the MaskInitialization code with the 
% following commands so the subsystem will be generated 
% according to the values of mask parameters.
% cfg.source = str2func('twiddle_stage_2');
% cfg.toplevel = gcb;
% args = {FFTSize, input_bit_width, add_latency, mult_latency, bram_latency, conv_latency, opt_target};
% xBlock(cfg, args);
% 
% To configure the xBlock call in debug mode, in which mode,
% autolayout will be performed every time a block is added,
% run the following commands:
% cfg.source = str2func('twiddle_stage_2');
% cfg.toplevel = gcb;
% cfg.debug = 1;
% args = {FFTSize, input_bit_width, add_latency, mult_latency, bram_latency, conv_latency, opt_target};
% xBlock(cfg, args);
% 
% To make the xBlock smart so it won't re-generate the
% subsystem if neither the arguments nor the scripts are
% changes, use as the following:
% cfg.source = str2func('twiddle_stage_2');
% cfg.toplevel = gcb;
% cfg.depend = {'twiddle_stage_2'};
% args = {FFTSize, input_bit_width, add_latency, mult_latency, bram_latency, conv_latency, opt_target};
% xBlock(cfg, args);
% 
% See also xBlock, xInport, xOutport, xSignal, xlsub2script.


%% inports
xlsub2_a = xInport('a');
xlsub2_b = xInport('b');
xlsub2_sync = xInport('sync');

%% outports
xlsub2_a_re = xOutport('a_re');
xlsub2_a_im = xOutport('a_im');
xlsub2_bw_re = xOutport('bw_re');
xlsub2_bw_im = xOutport('bw_im');
xlsub2_sync_out = xOutport('sync_out');

%% diagram

% block: twiddles_collections/twiddle_stage_2/c_to_ri
xlsub2_c_to_ri_out1 = xSignal;
xlsub2_c_to_ri_out2 = xSignal;
xlsub2_c_to_ri = xBlock(struct('source', 'casper_library_misc/c_to_ri', 'name', 'c_to_ri'), ...
                        struct('n_bits', input_bit_width, ...
                               'bin_pt', input_bit_width-1), ...
                        {xlsub2_a}, ...
                        {xlsub2_c_to_ri_out1, xlsub2_c_to_ri_out2});

% block: twiddles_collections/twiddle_stage_2/c_to_ri1
xlsub2_c_to_ri1_out1 = xSignal;
xlsub2_c_to_ri1_out2 = xSignal;
xlsub2_c_to_ri1 = xBlock(struct('source', 'casper_library_misc/c_to_ri', 'name', 'c_to_ri1'), ...
                         struct('n_bits', input_bit_width, ...
                                'bin_pt', input_bit_width-1), ...
                         {xlsub2_b}, ...
                         {xlsub2_c_to_ri1_out1, xlsub2_c_to_ri1_out2});

% block: twiddles_collections/twiddle_stage_2/convert
xlsub2_negate_out1 = xSignal;
xlsub2_convert_out1 = xSignal;
xlsub2_convert = xBlock(struct('source', 'Convert', 'name', 'convert'), ...
                        struct('n_bits', input_bit_width, ...
                               'bin_pt', input_bit_width - 1, ...
                               'overflow', 'Saturate', ...
                               'latency', conv_latency, ...
                               'pipeline', 'on'), ...
                        {xlsub2_negate_out1}, ...
                        {xlsub2_convert_out1});

% block: twiddles_collections/twiddle_stage_2/counter
xlsub2_delay7_out1 = xSignal;
xlsub2_counter_out1 = xSignal;
xlsub2_counter = xBlock(struct('source', 'Counter', 'name', 'counter'), ...
                        struct('n_bits', FFTSize - 1 , ...
                               'rst', 'on', ...
                               'use_behavioral_HDL', 'on'), ...
                        {xlsub2_delay7_out1}, ...
                        {xlsub2_counter_out1});

% block: twiddles_collections/twiddle_stage_2/delay0
xlsub2_delay0 = xBlock(struct('source', 'Delay', 'name', 'delay0'), ...
                       struct('latency', bram_latency+mult_latency+conv_latency+add_latency*2, ...
                              'reg_retiming', 'on'), ...
                       {xlsub2_c_to_ri_out1}, ...
                       {xlsub2_a_re});

% block: twiddles_collections/twiddle_stage_2/delay1
xlsub2_delay1 = xBlock(struct('source', 'Delay', 'name', 'delay1'), ...
                       struct('latency', bram_latency+mult_latency+conv_latency+add_latency*2, ...
                              'reg_retiming', 'on'), ...
                       {xlsub2_c_to_ri_out2}, ...
                       {xlsub2_a_im});

% block: twiddles_collections/twiddle_stage_2/delay2
xlsub2_slice_out1 = xSignal;
xlsub2_delay2_out1 = xSignal;
xlsub2_delay2 = xBlock(struct('source', 'Delay', 'name', 'delay2'), ...
                       struct('latency', mult_latency+conv_latency+add_latency*2-1, ...
                              'reg_retiming', 'on'), ...
                       {xlsub2_slice_out1}, ...
                       {xlsub2_delay2_out1});

% block: twiddles_collections/twiddle_stage_2/delay3
xlsub2_delay6_out1 = xSignal;
xlsub2_delay3_out1 = xSignal;
xlsub2_delay3 = xBlock(struct('source', 'Delay', 'name', 'delay3'), ...
                       struct('latency', mult_latency+conv_latency+add_latency*2-1, ...
                              'reg_retiming', 'on'), ...
                       {xlsub2_delay6_out1}, ...
                       {xlsub2_delay3_out1});

% block: twiddles_collections/twiddle_stage_2/delay4
xlsub2_delay4_out1 = xSignal;
xlsub2_delay4 = xBlock(struct('source', 'Delay', 'name', 'delay4'), ...
                       struct('latency', bram_latency+mult_latency+add_latency*2-2, ...
                              'reg_retiming', 'on'), ...
                       {xlsub2_convert_out1}, ...
                       {xlsub2_delay4_out1});

% block: twiddles_collections/twiddle_stage_2/delay5
xlsub2_delay5_out1 = xSignal;
xlsub2_delay5 = xBlock(struct('source', 'Delay', 'name', 'delay5'), ...
                       struct('latency', bram_latency, ...
                              'reg_retiming', 'on'), ...
                       {xlsub2_c_to_ri1_out1}, ...
                       {xlsub2_delay5_out1});

% block: twiddles_collections/twiddle_stage_2/delay6
xlsub2_delay6 = xBlock(struct('source', 'Delay', 'name', 'delay6'), ...
                       struct('latency', bram_latency, ...
                              'reg_retiming', 'on'), ...
                       {xlsub2_c_to_ri1_out2}, ...
                       {xlsub2_delay6_out1});

% block: twiddles_collections/twiddle_stage_2/delay7
xlsub2_delay7 = xBlock(struct('source', 'Delay', 'name', 'delay7'), ...
                       struct('latency', bram_latency, ...
                              'reg_retiming', 'on'), ...
                       {xlsub2_sync}, ...
                       {xlsub2_delay7_out1});

% block: twiddles_collections/twiddle_stage_2/delay8
xlsub2_delay8 = xBlock(struct('source', 'Delay', 'name', 'delay8'), ...
                       struct('latency', mult_latency+conv_latency+add_latency*2, ...
                              'reg_retiming', 'on'), ...
                       {xlsub2_delay7_out1}, ...
                       {xlsub2_sync_out});

% block: twiddles_collections/twiddle_stage_2/mux0
xlsub2_mux0 = xBlock(struct('source', 'Mux', 'name', 'mux0'), ...
                     struct('latency', 5), ...
                     {xlsub2_slice_out1, xlsub2_delay5_out1, xlsub2_delay6_out1}, ...
                     {xlsub2_bw_re});

% block: twiddles_collections/twiddle_stage_2/mux1
xlsub2_mux1 = xBlock(struct('source', 'Mux', 'name', 'mux1'), ...
                     struct('latency', 1), ...
                     {xlsub2_delay2_out1, xlsub2_delay3_out1, xlsub2_delay4_out1}, ...
                     {xlsub2_bw_im});

% block: twiddles_collections/twiddle_stage_2/negate
xlsub2_negate = xBlock(struct('source', 'Negate', 'name', 'negate'), ...
                       struct('n_bits', input_bit_width, ...
                              'bin_pt', input_bit_width-1, ...
                              'overflow', 'Saturate', ...
                              'latency', 1), ...
                       {xlsub2_c_to_ri1_out1}, ...
                       {xlsub2_negate_out1});

% block: twiddles_collections/twiddle_stage_2/slice
xlsub2_slice = xBlock(struct('source', 'Slice', 'name', 'slice'), ...
                      [], ...
                      {xlsub2_counter_out1}, ...
                      {xlsub2_slice_out1});



end

